kind: Service
apiVersion: v1
metadata:
  name: exampleservice1
spec:
  selector:
    app: myapp1
  ports:
  - protocol: "TCP"
    # Port accessible inside cluster
    port: 8082
    # Port to forward to inside the pod
    targetPort: 8002
    # Port accessible outside cluster
    nodePort: 30004
  type: NodePort